### ISSUE TITLE
알람 메시지

### ISSUE THREAD

**Issue by hyeongjudev** [goldforestdev/CommuterBus#56]
알람 메시지 - 추천
출근 알람 :  $정류장에 5분뒤에 도착 예정입니다. 
퇴근 알람 : 설정된 %에 곧 도착 예정입니다.

어디에 도착 예정이다가 있음 좋을것 같아요....다른 앱들(?)처럼.

**Comment by BurningDroid** [comment]
done - https://github.com/goldforestdev/CommuterBus/pull/57
